const TipsPageContentSection = () => {
    return (
        <div>
            <div>
                <h1 className="font-sora font-bold text-xl md:text-2xl  lg:text-3xl mb-3 scroll-mt-[100px]" id="para_1">1. Research Your Destination</h1>
                <p className="mb-8 font-sora text-base text-black/70">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quod quibusdam fugiat, et labore adipisci hic explicabo ratione eligendi? Culpa inventore voluptas obcaecati, doloribus non ipsam ipsum voluptates minus ab. Atque maiores perferendis provident quos magni nemo dignissimos facere, nihil ex odio nam vitae, dicta reprehenderit minima dolor! Nam eos dolores necessitatibus hic fuga consectetur, enim porro nihil nemo labore saepe non illo quo placeat numquam debitis dolorem explicabo similique repellendus?</p>

                <h1 className="font-sora font-bold text-xl md:text-2xl  lg:text-3xl mb-3 scroll-mt-[100px]" id="para_2">2. Create a Flexible Itinerary</h1>
                <p className="mb-8 font-sora text-base text-black/70">Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero, ipsam atque. Incidunt earum fugit odio totam. Magni vel repellendus fuga corporis quis eos, modi, quidem sed animi eveniet illum sint accusamus, in consectetur at ut reiciendis tenetur porro est laborum! Dolore reprehenderit omnis delectus fugiat dolores provident porro aliquid perferendis neque illum dicta accusantium magni hic ipsum odit laborum quos, doloribus voluptatem animi. Itaque quasi harum quibusdam soluta perferendis fugit aspernatur, labore nam asperiores, voluptate expedita repudiandae ad ipsam doloremque.</p>

                <h1 className="font-sora font-bold text-xl md:text-2xl  lg:text-3xl mb-3 scroll-mt-[100px]" id="para_3">3. Pack Smart and Light</h1>
                <p className="mb-8 font-sora text-base text-black/70">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic omnis ut aliquam animi repellendus reprehenderit, neque at minima fugiat sint esse, optio laborum! Accusamus perspiciatis vel quas temporibus quos sed deleniti repellat asperiores totam quasi ad, cupiditate eius consequatur officiis! Voluptas eos ab repudiandae neque nobis recusandae mollitia saepe quos temporibus similique, laudantium natus libero at asperiores maiores, iure a quam ducimus praesentium tempore ipsam nisi. Maxime quos voluptates ipsam nulla iusto nostrum ducimus iste ad vitae facere, quisquam repellat?</p>

                <h1 className="font-sora font-bold text-xl md:text-2xl  lg:text-3xl mb-3 scroll-mt-[100px]" id="para_4">4. Use Travel Organizers</h1>
                <p className="mb-8 font-sora text-base text-black/70">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic omnis ut aliquam animi repellendus reprehenderit, neque at minima fugiat sint esse, optio laborum! Accusamus perspiciatis vel quas temporibus quos sed deleniti repellat asperiores totam quasi ad, cupiditate eius consequatur officiis! Voluptas eos ab repudiandae neque nobis recusandae mollitia saepe quos temporibus similique, laudantium natus libero at asperiores maiores, iure a quam ducimus praesentium tempore ipsam nisi. Maxime quos voluptates ipsam nulla iusto nostrum ducimus iste ad vitae facere, quisquam repellat?</p>

                <h1 className="font-sora font-bold text-xl md:text-2xl  lg:text-3xl mb-3 scroll-mt-[100px]" id="para_5">5. Secure Important Documents</h1>
                <p className="mb-8 font-sora text-base text-black/70">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic omnis ut aliquam animi repellendus reprehenderit, neque at minima fugiat sint esse, optio laborum! Accusamus perspiciatis vel quas temporibus quos sed deleniti repellat asperiores totam quasi ad, cupiditate eius consequatur officiis! Voluptas eos ab repudiandae neque nobis recusandae mollitia saepe quos temporibus similique, laudantium natus libero at asperiores maiores, iure a quam ducimus praesentium tempore ipsam nisi. Maxime quos voluptates ipsam nulla iusto nostrum ducimus iste ad vitae facere, quisquam repellat?</p>

                <h1 className="font-sora font-bold text-xl md:text-2xl  lg:text-3xl mb-3 scroll-mt-[100px]" id="para_6">6. Invest in Travel Insurance</h1>
                <p className="mb-8 font-sora text-base text-black/70">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic omnis ut aliquam animi repellendus reprehenderit, neque at minima fugiat sint esse, optio laborum! Accusamus perspiciatis vel quas temporibus quos sed deleniti repellat asperiores totam quasi ad, cupiditate eius consequatur officiis! Voluptas eos ab repudiandae neque nobis recusandae mollitia saepe quos temporibus similique, laudantium natus libero at asperiores maiores, iure a quam ducimus praesentium tempore ipsam nisi. Maxime quos voluptates ipsam nulla iusto nostrum ducimus iste ad vitae facere, quisquam repellat?</p>

                <h1 className="font-sora font-bold text-xl md:text-2xl  lg:text-3xl mb-3 scroll-mt-[100px]" id="para_7">7. Stay Hydrated and Eat Wisely</h1>
                <p className="mb-8 font-sora text-base text-black/70">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic omnis ut aliquam animi repellendus reprehenderit, neque at minima fugiat sint esse, optio laborum! Accusamus perspiciatis vel quas temporibus quos sed deleniti repellat asperiores totam quasi ad, cupiditate eius consequatur officiis! Voluptas eos ab repudiandae neque nobis recusandae mollitia saepe quos temporibus similique, laudantium natus libero at asperiores maiores, iure a quam ducimus praesentium tempore ipsam nisi. Maxime quos voluptates ipsam nulla iusto nostrum ducimus iste ad vitae facere, quisquam repellat?</p>

                <h1 className="font-sora font-bold text-xl md:text-2xl  lg:text-3xl mb-3 scroll-mt-[100px]" id="para_8">8. Learn Basic Phrases of the Local Language</h1>
                <p className="mb-8 font-sora text-base text-black/70">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic omnis ut aliquam animi repellendus reprehenderit, neque at minima fugiat sint esse, optio laborum! Accusamus perspiciatis vel quas temporibus quos sed deleniti repellat asperiores totam quasi ad, cupiditate eius consequatur officiis! Voluptas eos ab repudiandae neque nobis recusandae mollitia saepe quos temporibus similique, laudantium natus libero at asperiores maiores, iure a quam ducimus praesentium tempore ipsam nisi. Maxime quos voluptates ipsam nulla iusto nostrum ducimus iste ad vitae facere, quisquam repellat?</p>

                <h1 className="font-sora font-bold text-xl md:text-2xl  lg:text-3xl mb-3 scroll-mt-[100px]" id="para_9">9. Use Public Transport</h1>
                <p className="mb-8 font-sora text-base text-black/70">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic omnis ut aliquam animi repellendus reprehenderit, neque at minima fugiat sint esse, optio laborum! Accusamus perspiciatis vel quas temporibus quos sed deleniti repellat asperiores totam quasi ad, cupiditate eius consequatur officiis! Voluptas eos ab repudiandae neque nobis recusandae mollitia saepe quos temporibus similique, laudantium natus libero at asperiores maiores, iure a quam ducimus praesentium tempore ipsam nisi. Maxime quos voluptates ipsam nulla iusto nostrum ducimus iste ad vitae facere, quisquam repellat?</p>

                <h1 className="font-sora font-bold text-xl md:text-2xl  lg:text-3xl mb-3 scroll-mt-[100px]" id="para_10">10. Keep Your Valuables Safe</h1>
                <p className="mb-8 font-sora text-base text-black/70">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic omnis ut aliquam animi repellendus reprehenderit, neque at minima fugiat sint esse, optio laborum! Accusamus perspiciatis vel quas temporibus quos sed deleniti repellat asperiores totam quasi ad, cupiditate eius consequatur officiis! Voluptas eos ab repudiandae neque nobis recusandae mollitia saepe quos temporibus similique, laudantium natus libero at asperiores maiores, iure a quam ducimus praesentium tempore ipsam nisi. Maxime quos voluptates ipsam nulla iusto nostrum ducimus iste ad vitae facere, quisquam repellat?</p>

                <h1 className="font-sora font-bold text-xl md:text-2xl  lg:text-3xl mb-3 scroll-mt-[100px]" id="para_11">11. Carry a Universal Adapter and Power Bank</h1>
                <p className="mb-8 font-sora text-base text-black/70">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic omnis ut aliquam animi repellendus reprehenderit, neque at minima fugiat sint esse, optio laborum! Accusamus perspiciatis vel quas temporibus quos sed deleniti repellat asperiores totam quasi ad, cupiditate eius consequatur officiis! Voluptas eos ab repudiandae neque nobis recusandae mollitia saepe quos temporibus similique, laudantium natus libero at asperiores maiores, iure a quam ducimus praesentium tempore ipsam nisi. Maxime quos voluptates ipsam nulla iusto nostrum ducimus iste ad vitae facere, quisquam repellat?</p>

                <h1 className="font-sora font-bold text-xl md:text-2xl  lg:text-3xl mb-3 scroll-mt-[100px]" id="para_12">12. Be Mindful of Local Customs</h1>
                <p className="mb-8 font-sora text-base text-black/70">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic omnis ut aliquam animi repellendus reprehenderit, neque at minima fugiat sint esse, optio laborum! Accusamus perspiciatis vel quas temporibus quos sed deleniti repellat asperiores totam quasi ad, cupiditate eius consequatur officiis! Voluptas eos ab repudiandae neque nobis recusandae mollitia saepe quos temporibus similique, laudantium natus libero at asperiores maiores, iure a quam ducimus praesentium tempore ipsam nisi. Maxime quos voluptates ipsam nulla iusto nostrum ducimus iste ad vitae facere, quisquam repellat?</p>

                <h1 className="font-sora font-bold text-xl md:text-2xl  lg:text-3xl mb-3 scroll-mt-[100px]" id="para_13">13. Budget and Track Expenses</h1>
                <p className="mb-8 font-sora text-base text-black/70">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic omnis ut aliquam animi repellendus reprehenderit, neque at minima fugiat sint esse, optio laborum! Accusamus perspiciatis vel quas temporibus quos sed deleniti repellat asperiores totam quasi ad, cupiditate eius consequatur officiis! Voluptas eos ab repudiandae neque nobis recusandae mollitia saepe quos temporibus similique, laudantium natus libero at asperiores maiores, iure a quam ducimus praesentium tempore ipsam nisi. Maxime quos voluptates ipsam nulla iusto nostrum ducimus iste ad vitae facere, quisquam repellat?</p>

                <h1 className="font-sora font-bold text-xl md:text-2xl  lg:text-3xl mb-3 scroll-mt-[100px]" id="para_14">14. Keep Emergency Contacts Handy</h1>
                <p className="mb-8 font-sora text-base text-black/70">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic omnis ut aliquam animi repellendus reprehenderit, neque at minima fugiat sint esse, optio laborum! Accusamus perspiciatis vel quas temporibus quos sed deleniti repellat asperiores totam quasi ad, cupiditate eius consequatur officiis! Voluptas eos ab repudiandae neque nobis recusandae mollitia saepe quos temporibus similique, laudantium natus libero at asperiores maiores, iure a quam ducimus praesentium tempore ipsam nisi. Maxime quos voluptates ipsam nulla iusto nostrum ducimus iste ad vitae facere, quisquam repellat?</p>

                <h1 className="font-sora font-bold text-xl md:text-2xl  lg:text-3xl mb-3 scroll-mt-[100px]" id="para_15">15. Capture Memories but Stay Present</h1>
                <p className="mb-8 font-sora text-base text-black/70">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic omnis ut aliquam animi repellendus reprehenderit, neque at minima fugiat sint esse, optio laborum! Accusamus perspiciatis vel quas temporibus quos sed deleniti repellat asperiores totam quasi ad, cupiditate eius consequatur officiis! Voluptas eos ab repudiandae neque nobis recusandae mollitia saepe quos temporibus similique, laudantium natus libero at asperiores maiores, iure a quam ducimus praesentium tempore ipsam nisi. Maxime quos voluptates ipsam nulla iusto nostrum ducimus iste ad vitae facere, quisquam repellat?</p>

            </div>
        </div>
    );
};

export default TipsPageContentSection;